#!/usr/bin/env python3
"""Regenerate every page of 555185.com from _src/. Usage: python3 build.py"""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "_src"))
from numdata import DIGITS, CODES
from greetings import GREETINGS
import tools_pages, meanings, guides, pages
from layout import DOMAIN

def w(rel, content):
    p = os.path.join(HERE, rel); os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", encoding="utf-8").write(content)

# Lunar New Year dates 1920–2045 (needs: pip install lunardate)
try:
    from lunardate import LunarDate
    w("assets/data/cny.json", json.dumps({y: LunarDate(y, 1, 1).to_solar_date().isoformat() for y in range(1920, 2046)}))
except ImportError:
    print("lunardate not installed — keeping existing assets/data/cny.json")

# data for the browser
codes = [dict(num=c[0], zh=c[1], py=c[2], en=c[3], luck=c[4], cat=c[5]) for c in CODES]
w("assets/js/numdata.js", "/* generated by build.py — edit _src/numdata.py */\nwindow.NUMDATA=" +
  json.dumps({"digits": DIGITS, "codes": codes}, ensure_ascii=False) + ";\nwindow.GREETINGS=" +
  json.dumps([dict(c=a, zh=b, py=c, en=d) for a, b, c, d in GREETINGS], ensure_ascii=False) + ";\n")

out = []
out += tools_pages.build()
m, codes_full = meanings.build(); out += m
out += guides.build()
out += pages.build(codes_full, guides.G)

BASE404 = '<meta charset="utf-8">\n<script>document.write(\'<base href="\'+(location.pathname.indexOf("/555185-com/")===0?"/555185-com/":"/")+\'">\')</script>'
for path, html in out:
    if path == "404.html":
        html = html.replace('<meta charset="utf-8">', BASE404, 1).replace('data-root="./"', 'data-root=""')
    w(path, html)

skip = {"404.html", "thank-you.html"}
urls = []
for path, _ in out:
    if path in skip: continue
    u = DOMAIN + "/" + (path[:-10] if path.endswith("index.html") else path)
    pr = "1.0" if path == "index.html" else "0.9" if path.startswith("tools/") else "0.8" if path.startswith(("guides/", "quote")) else "0.6"
    urls.append(f"<url><loc>{u}</loc><lastmod>2026-10-05</lastmod><priority>{pr}</priority></url>")
w("sitemap.xml", '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + "\n".join(sorted(urls)) + "\n</urlset>\n")
w("robots.txt", f"User-agent: *\nAllow: /\nDisallow: /thank-you.html\nDisallow: /_src/\nSitemap: {DOMAIN}/sitemap.xml\n")
# Open Graph image (optional — needs Pillow)
try:
    from PIL import Image, ImageDraw, ImageFont
    def font(sz):
        for p in ["/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"]:
            if os.path.exists(p): return ImageFont.truetype(p, sz)
        return ImageFont.load_default()
    im = Image.new("RGB", (1200, 630), "#C8102E"); d = ImageDraw.Draw(im)
    d.rectangle([30, 30, 1170, 600], outline="#E5C25A", width=6)
    d.text((600, 230), "555185", font=font(170), fill="#FFD86B", anchor="mm")
    d.text((600, 380), "Red envelopes · Lucky numbers · Number codes", font=font(44), fill="#FFFFFF", anchor="mm")
    d.text((600, 470), "From 555 (tears) to 185 (fortune)", font=font(36), fill="#FFE8A3", anchor="mm")
    os.makedirs(os.path.join(HERE, "assets/img"), exist_ok=True); im.save(os.path.join(HERE, "assets/img/og.png"))
except Exception as e:
    print("OG image skipped:", e)
print(f"Built {len(out)} pages")
