GREETINGS = [
 ("Lunar New Year", "恭喜发财", "gōng xǐ fā cái", "Wishing you prosperity"),
 ("Lunar New Year", "新年快乐", "xīn nián kuài lè", "Happy New Year"),
 ("Lunar New Year", "万事如意", "wàn shì rú yì", "May all things go as you wish"),
 ("Lunar New Year", "岁岁平安", "suì suì píng ān", "Peace and safety year after year"),
 ("Lunar New Year", "年年有余", "nián nián yǒu yú", "Abundance (surplus) every year"),
 ("Lunar New Year", "大吉大利", "dà jí dà lì", "Great luck and great profit"),
 ("Lunar New Year", "身体健康", "shēn tǐ jiàn kāng", "Wishing you good health"),
 ("Lunar New Year", "心想事成", "xīn xiǎng shì chéng", "May your wishes come true"),
 ("Lunar New Year", "步步高升", "bù bù gāo shēng", "Rise higher with every step"),
 ("Lunar New Year", "红包拿来", "hóng bāo ná lái", "Hand over the red envelope! (playful)"),
 ("Year of the Goat 2027", "羊年大吉", "yáng nián dà jí", "Great luck in the Year of the Goat"),
 ("Year of the Goat 2027", "三羊开泰", "sān yáng kāi tài", "Three goats bring peace and prosperity"),
 ("Year of the Goat 2027", "喜气洋洋", "xǐ qì yáng yáng", "Brimming with joy (洋 puns on 羊)"),
 ("Year of the Goat 2027", "羊年吉祥", "yáng nián jí xiáng", "An auspicious Goat year"),
 ("Wedding", "百年好合", "bǎi nián hǎo hé", "A hundred years of harmony"),
 ("Wedding", "永结同心", "yǒng jié tóng xīn", "Hearts united forever"),
 ("Wedding", "早生贵子", "zǎo shēng guì zǐ", "May you soon have a precious child"),
 ("Wedding", "白头偕老", "bái tóu xié lǎo", "Grow old together"),
 ("Wedding", "天作之合", "tiān zuò zhī hé", "A match made in heaven"),
 ("Birthday", "生日快乐", "shēng rì kuài lè", "Happy birthday"),
 ("Birthday", "福如东海", "fú rú dōng hǎi", "Fortune as vast as the Eastern Sea"),
 ("Birthday", "寿比南山", "shòu bǐ nán shān", "Longevity like the Southern Mountains"),
 ("Business", "生意兴隆", "shēng yì xīng lóng", "May your business prosper"),
 ("Business", "开业大吉", "kāi yè dà jí", "Great luck on your opening"),
 ("Business", "财源广进", "cái yuán guǎng jìn", "May wealth flow in from all sides"),
 ("Business", "一本万利", "yī běn wàn lì", "Small investment, ten-thousandfold profit"),
 ("Baby / full month", "健康成长", "jiàn kāng chéng zhǎng", "Grow up healthy"),
 ("Baby / full month", "聪明伶俐", "cōng míng líng lì", "Bright and clever"),
 ("Study / exams", "金榜题名", "jīn bǎng tí míng", "Top of the exam list"),
 ("Study / exams", "学业进步", "xué yè jìn bù", "Progress in your studies"),
]
