# Number-code dictionary — single source of truth for meaning pages and the in-browser decoder.
# luck: lucky | unlucky | love | slang | mixed | neutral
DIGITS = {
 "0": dict(py="líng", zh="零", sounds="你 nǐ (you, in texting) · 灵 líng (clever, effective)", luck="neutral",
          note="Zero is a placeholder for ‘you’ in love codes (e.g. 530 我想你). On its own it is neutral; in amounts, round zeros look generous and tidy."),
 "1": dict(py="yī / yāo", zh="一 / 幺", sounds="要 yào (want, will) · 一 yī (one, whole)", luck="neutral",
          note="In phone and plate numbers 1 is read ‘yāo’, which sounds like 要 (want / will). 1 also stands for 一 in 一生一世 (a lifetime), so it powers codes like 1314."),
 "2": dict(py="èr / liǎng", zh="二 / 两", sounds="爱 ài (love, in texting) · 双 (pairs)", luck="lucky",
          note="‘Good things come in pairs’ (好事成双). Even amounts are standard for weddings and celebrations. In love codes 2 stands for 爱 (love)."),
 "3": dict(py="sān", zh="三", sounds="生 shēng (life, birth) · 散 sàn (to scatter / split)", luck="mixed",
          note="In Cantonese 3 (saam) echoes 生 (life), so it is welcome in Hong Kong. In Mandarin some hear 散 (to split up), so couples sometimes avoid it."),
 "4": dict(py="sì", zh="四", sounds="死 sǐ (death) · 是 shì (yes, in texting)", luck="unlucky",
          note="The most avoided digit in Chinese culture because 四 sì sounds like 死 sǐ (death). Many buildings skip 4th / 14th floors. Never put an amount containing 4 in a red envelope."),
 "5": dict(py="wǔ", zh="五", sounds="我 wǒ (I / me) · 呜 wū (crying) · 无 wú (without)", luck="neutral",
          note="5 is the workhorse of texting slang: it means ‘me’ in 520 (I love you) and ‘boo-hoo’ in 555. It also links to the Five Elements (五行). Neutral in amounts."),
 "6": dict(py="liù", zh="六", sounds="溜 liù / 流 liú (smooth, flowing) · 顺 (六六大顺)", luck="lucky",
          note="‘Everything goes smoothly’ — 六六大顺. 66 and 666 are popular gift amounts and, online, 666 means ‘awesome’."),
 "7": dict(py="qī", zh="七", sounds="起 qǐ (rise) · 气 qì (anger) · 去 qù (go, in texting) · 亲 qīn (kiss)", luck="mixed",
          note="7 is mixed: it can mean ‘rise’ (起) or ‘togetherness’ (in 七夕, Chinese Valentine’s), but also 气 (anger) and appears in insults like 748. The 7th lunar month is Ghost Month."),
 "8": dict(py="bā", zh="八", sounds="发 fā (to prosper) · 吧 ba · 爸 (dad)", luck="lucky",
          note="The luckiest number for wealth: 八 bā rhymes with 发 fā (to prosper, get rich), especially in Cantonese ‘baat / faat’. Beijing opened the 2008 Olympics on 08-08-08 at 8:08 pm."),
 "9": dict(py="jiǔ", zh="九", sounds="久 jiǔ (long-lasting) · 就 jiù (just) · 救 jiù (save)", luck="lucky",
          note="9 sounds like 久 (forever, long-lasting) — perfect for weddings and love gifts (999 roses). Historically associated with the emperor."),
}

CODES = [
 # num, zh, pinyin, short meaning, luck, category, description, example zh, example en
 ("555","呜呜呜","wū wū wū","Boo-hoo — crying / sobbing","slang","Emotion",
  "The single most recognised Chinese texting code for crying. Each 5 (wǔ) mimics the sobbing sound 呜 (wū). It ranges from real sadness to playful whining or mock despair. More fives = more drama: 5555, 55555. Note: in Thai, 555 means ‘hahaha’ — the opposite!",
  "又要加班了，555", "Overtime again… boo-hoo."),
 ("5555","呜呜呜呜","wū wū wū wū","Loud sobbing — extra-dramatic crying","slang","Emotion",
  "An intensified 555. Used for exaggerated, often comedic despair — exam results, cancelled plans, an empty wallet before payday.",
  "红包被抢光了5555", "All the red packets got grabbed — waaah."),
 ("185","要发我","yāo bā wǔ","‘Prosperity — to me!’ (playful reading)","lucky","Wealth",
  "185 is read yāo-bā-wǔ in phone style: 1 = 要 (want / will), 8 = 发 (prosper), 5 = 我 (me). Strung together it gives the cheeky reading 要发我 — ‘prosperity, come to me’ — or ‘send me (a red packet)’. This is a constructed homophone reading, not established slang. Separately, ‘185’ is widely used in Chinese social media as shorthand for a 185 cm (6′1″) height, a popular ideal in dating culture.",
  "555 … 185！", "Boo-hoo… now pay me / prosperity to me!"),
 ("555185","呜呜呜，要发我","wū wū wū, yāo fā wǒ","From tears to fortune — ‘boo-hoo… now prosperity comes to me’","lucky","Story",
  "Read as two halves: 555 (呜呜呜, crying) + 185 (要发我, ‘prosperity to me’). The story: stop crying about money — the red packet is on its way. It is a playful, memorable homophone chain and the brand idea behind this website. It contains no 4, has a doubled-up 5 rhythm and ends on the lucky 8-5 ‘prosper-me’ beat.",
  "555185 — 别哭了，红包来了！", "555185 — stop crying, the red packet is here!"),
 ("520","我爱你","wǒ ài nǐ","I love you","love","Love",
  "The most famous Chinese number code. 5-2-0 (wǔ-èr-líng) loosely echoes 我爱你 (wǒ ài nǐ). May 20 (5/20) has become an unofficial online Valentine’s Day in China, with ¥520 transfers and red packets between couples. 5201314 ranked among Google India’s top ‘meaning’ searches in 2025.",
  "520快乐！给你发个520的红包。", "Happy 520! Sending you a ¥520 red packet."),
 ("521","我愿意 / 我爱你","wǒ yuàn yì / wǒ ài nǐ","I do / I love you","love","Love",
  "A companion to 520, often read as 我愿意 (‘I’m willing / I do’). May 21 is a popular wedding-registration and proposal date.",
  "你问我愿不愿意？521！", "You ask if I will? 521 — I do!"),
 ("1314","一生一世","yī shēng yī shì","For a whole lifetime / forever","love","Love",
  "1-3-1-4 sounds like 一生一世 (one life, one world — ‘forever’). Note the 4 here is accepted because the phrase is romantic. ¥1,314 is a classic wedding or anniversary amount.",
  "我会爱你1314。", "I’ll love you forever."),
 ("5201314","我爱你一生一世","wǒ ài nǐ yī shēng yī shì","I love you forever","love","Love",
  "520 + 1314 = ‘I love you for a lifetime.’ Used in proposals, wedding red packets (¥5,201.314 is a joke; ¥520 or ¥1,314 are real) and couple usernames. It ranked #5 in Google India’s 2025 ‘meaning’ searches.",
  "5201314，嫁给我吧！", "I love you forever — marry me!"),
 ("1314520","一生一世我爱你","yī shēng yī shì wǒ ài nǐ","For a lifetime, I love you","love","Love",
  "The reversed form of 5201314, same meaning, sometimes chosen for phone numbers and gift amounts on wedding anniversaries.",
  "一生一世我爱你——1314520", "For a lifetime, I love you."),
 ("530","我想你","wǒ xiǎng nǐ","I miss you","love","Love",
  "5 = 我 (I), 3 = 想 (miss — sān/xiǎng), 0 = 你 (you). Common between long-distance couples.",
  "530，早点回来。", "Miss you, come back soon."),
 ("3344","生生世世","shēng shēng shì shì","Life after life — eternal love","love","Love",
  "Doubles of 3 and 4 echo 生生世世 (through every lifetime). A romantic code that ‘redeems’ the 4.",
  "3344，永不分离。", "Life after life, never apart."),
 ("9420","就是爱你","jiù shì ài nǐ","It’s just that I love you","love","Love",
  "9 = 就 (just), 4 = 是 (is), 2 = 爱 (love), 0 = 你 (you).",
  "不为什么，9420。", "No reason — I just love you."),
 ("770","亲亲你","qīn qīn nǐ","Kiss you","love","Love",
  "Two 7s (qī) sound like 亲亲 (kiss kiss), 0 = 你 (you).",
  "晚安，770。", "Good night, kisses."),
 ("7758258","亲亲我吧，爱我吧","qīn qīn wǒ ba, ài wǒ ba","Kiss me, love me","love","Love",
  "A classic late-2000s QQ-era love code: 77 (亲亲 kiss) 5 (我 me) 8 (吧) 2 (爱 love) 5 (我) 8 (吧).",
  "7758258～", "Kiss me, love me~"),
 ("1798","一起走吧","yī qǐ zǒu ba","Let’s go together","love","Love",
  "1 = 一, 7 = 起 (qǐ), 9 = 走 (zǒu, loosely), 8 = 吧. An invitation to stay together.",
  "1798，不管去哪里。", "Let’s go together, wherever."),
 ("8013","伴你一生","bàn nǐ yī shēng","By your side for a lifetime","love","Love",
  "8 = 伴 (bàn, accompany), 0 = 你, 1 = 一, 3 = 生. A vow-style code.",
  "8013，我说到做到。", "By your side for life — I mean it."),
 ("9277","就爱亲亲","jiù ài qīn qīn","Just love kissing (you)","love","Love",
  "9 = 就, 2 = 爱, 77 = 亲亲.", "9277 😘", "Love kissing you."),
 ("88","拜拜 / 发发","bā bā / fā fā","Bye-bye — or double prosperity","lucky","Greeting",
  "Online, 88 (bā bā) means bye-bye. In money, 88 is double prosperity (发发) — one of the most popular red-envelope amounts across Asia.",
  "我先下线了，88！", "Logging off — bye!"),
 ("886","拜拜了","bā bā le","Bye-bye (I’m off)","slang","Greeting",
  "88 + 6 (liù ≈ le). A casual sign-off in chats and forums.",
  "明天见，886。", "See you tomorrow, bye."),
 ("666","溜溜溜","liù liù liù","Awesome! / so smooth / well played","lucky","Praise",
  "Gamers and live-stream chats spam 666 to praise a skilful move. Unlike the West, 666 is lucky in China (六六大顺 — everything smooth). ¥666 is a popular celebration amount.",
  "这操作太666了！", "That move was awesome!"),
 ("6666","溜溜溜溜","liù liù liù liù","Super awesome","lucky","Praise",
  "An intensified 666; also a premium ‘smooth sailing’ number for phones, plates and business amounts.",
  "6666，大神！", "Legend — awesome!"),
 ("233","笑死我了","èr sān sān","LOL — laughing hard","slang","Emotion",
  "Comes from emoticon #233 on the Mop (猫扑) forum, a face pounding the floor with laughter. Longer = harder: 23333333.",
  "哈哈哈2333", "Hahaha LOL."),
 ("2333","哈哈哈","èr sān sān sān","LOL (extended)","slang","Emotion",
  "An extended 233 — the more 3s, the harder the laugh. Ubiquitous in Bilibili bullet comments.", "23333333", "LOOOOL."),
 ("748","去死吧","qù sǐ ba","Get lost / go to hell","unlucky","Insult",
  "7 = 去 (go), 4 = 死 (die), 8 = 吧. A rude brush-off — never use as a gift amount or phone suffix you want to show off.",
  "你走开，748！", "Go away, get lost!"),
 ("7456","气死我了","qì sǐ wǒ le","I’m so angry / infuriating","unlucky","Emotion",
  "7 = 气 (anger), 4 = 死 (to death), 5 = 我 (me), 6 = 了 (le).",
  "又堵车，7456！", "Traffic again — so infuriating!"),
 ("995","救救我","jiù jiù wǒ","Help me / save me","slang","Emotion",
  "99 = 救救 (save), 5 = 我. Used jokingly about deadlines and exams.",
  "明天考试，995！", "Exam tomorrow — save me!"),
 ("94","就是","jiù shì","Exactly / that’s right","slang","Agreement",
  "9 = 就, 4 = 是 (shì, ‘is’). One of the few slang uses where 4 means ‘yes’, not ‘death’.",
  "94！我也这么想。", "Exactly! I think so too."),
 ("9494","就是就是","jiù shì jiù shì","Totally! Absolutely right","slang","Agreement",
  "A doubled 94 for enthusiastic agreement.", "9494，你说得对！", "Totally, you’re right!"),
 ("484","是不是","shì bú shì","Is it or not? / right?","slang","Question",
  "4 = 是, 8 = 不 (bù, loosely), 4 = 是. A texting tag question.", "你喜欢她484？", "You like her, right?"),
 ("584","我发誓","wǒ fā shì","I swear","slang","Promise",
  "5 = 我, 8 = 发, 4 = 誓 (shì, oath).", "584，下次不迟到了。", "I swear I won’t be late next time."),
 ("514","我要死 / 无意思","wǒ yào sǐ","‘I’m dying’ (exasperation)","unlucky","Emotion",
  "5 = 我, 1 = 要, 4 = 死. A dramatic complaint; avoid in amounts and dates for gifts.",
  "作业太多了，514。", "So much homework — I’m dying."),
 ("14","要死","yāo sǐ","‘Want to die’ — avoided","unlucky","Taboo",
  "Read phone-style as yāo-sì ≈ 要死 (‘going to die’). This is why many buildings skip the 14th floor and why 14 is avoided in plates, prices and red-envelope amounts.",
  "电梯没有14楼。", "The lift has no 14th floor."),
 ("250","二百五","èr bǎi wǔ","Idiot / fool — never give 250","unlucky","Insult",
  "二百五 is a classic insult meaning a foolish person. Giving ¥250 (or 2,500) in a red envelope is a well-known faux pas — round it to 200, 260 or 288.",
  "你真是个二百五！", "You’re such an idiot!"),
 ("13","十三点","shí sān diǎn","Silly / scatter-brained (Shanghai)","mixed","Insult",
  "In Shanghainese slang 十三点 describes a silly, scatter-brained person. Western ‘unlucky 13’ also matters to international audiences — avoid in global pricing.",
  "她有点十三点。", "She’s a bit scatter-brained."),
 ("286","落后","èr bā liù","Outdated, behind the times","slang","Tech",
  "A nod to the 1980s Intel 286 computer — calling someone 286 means they are slow or out of touch.",
  "你还用这个？太286了。", "You still use that? So outdated."),
 ("51","我要","wǒ yào","I want","neutral","Desire",
  "5 = 我, 1 = 要 (yāo). Also May 1 — Labour Day ‘golden week’, a major shopping and travel holiday.",
  "51，我要红包！", "I want a red packet!"),
 ("518","我要发","wǒ yào fā","I’m going to prosper","lucky","Wealth",
  "One of the most coveted business numbers: 5 = 我, 1 = 要, 8 = 发 (prosper). Popular for shop phone lines, plate numbers, prices (¥518) and opening dates (May 18).",
  "开业大吉，518！", "Grand opening — I will prosper!"),
 ("168","一路发","yī lù fā","Prosper all the way","lucky","Wealth",
  "1 = 一, 6 = 路 (liù / lù), 8 = 发. ‘Prosperity all along the road’ — a staple for businesses, prices and red packets (¥168, ¥1,688).",
  "祝你一路发，168！", "Wishing you prosperity all the way!"),
 ("1688","一路发发","yī lù fā fā","Prosperity all the way, doubled","lucky","Wealth",
  "An upgraded 168 — common for weddings, shop openings and corporate red packets (¥1,688).",
  "开张红包1688。", "Opening-day red packet: 1,688."),
 ("188","要发发","yāo fā fā","Prosper, prosper","lucky","Wealth",
  "1 (yāo, 要) + 88 (发发). A friendly mid-range gift amount: ¥188 / $188.", "188的红包刚刚好。", "A 188 red packet is just right."),
 ("888","发发发","fā fā fā","Triple prosperity","lucky","Wealth",
  "Wealth, wealth, wealth — one of the most auspicious amounts and prices. Premium phone numbers and plates ending in 888 sell at large premiums.",
  "新年红包888！", "New Year red packet: 888!"),
 ("8888","发发发发","fā fā fā fā","Prosperity ×4 (and no 4 in sight)","lucky","Wealth",
  "The ultimate wealth repdigit for big-ticket gifts and business milestones.", "八八八八，大吉大利！", "8888 — great luck and profit!"),
 ("99","久久","jiǔ jiǔ","Long-lasting (forever)","lucky","Love",
  "9 = 久 (long-lasting). ¥99 or 999 roses signal lasting love. The 9th day of the 9th month is the Double Ninth (Chongyang) festival honouring elders.",
  "长长久久，99。", "Together forever."),
 ("999","久久久","jiǔ jiǔ jiǔ","Everlasting","lucky","Love",
  "Three 9s = forever and ever. Popular for anniversary gifts and wedding amounts (¥999).", "999朵玫瑰", "999 roses."),
 ("66","六六大顺","liù liù dà shùn","Everything goes smoothly","lucky","Wealth",
  "A favourite birthday / exam / new-job amount (¥66, ¥666).", "66大顺！", "Smooth sailing!"),
 ("18","要发","yāo fā","Will prosper","lucky","Wealth",
  "1 (yāo, 要) + 8 (发). Also the age of adulthood. ¥18 / ¥188 are friendly amounts for younger relatives.",
  "18岁生日快乐，要发！", "Happy 18th — prosper!"),
 ("0437","你是神经","nǐ shì shén jīng","You’re crazy","slang","Insult",
  "0 = 你, 4 = 是, 3 = 神 (shén), 7 = 经 (jīng, loosely). A teasing jab between friends.", "0437啊你！", "You’re nuts!"),
]
